# Generated by Django 2.2.7 on 2020-03-28 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='商品名称')),
                ('level', models.PositiveSmallIntegerField(default=2, null=True, verbose_name='商品等级')),
                ('price', models.FloatField(null=True, verbose_name='价格')),
                ('parent_kind', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='goods_app.Goods', verbose_name='所属种类')),
            ],
        ),
    ]
