# Generated by Django 2.2.7 on 2020-03-28 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='parent_kind',
        ),
        migrations.AddField(
            model_name='goods',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kinds', to='goods_app.Goods', verbose_name='所属种类'),
        ),
    ]
