# Generated by Django 2.2.7 on 2020-03-28 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods_app', '0002_auto_20200328_2332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='level',
        ),
        migrations.AlterField(
            model_name='goods',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='商品名称'),
        ),
    ]
