# Generated by Django 2.2.7 on 2020-03-29 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods_app', '0003_auto_20200329_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='inventory',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='库存量'),
        ),
    ]
